---
go:
    version: 1.20
repository:
    path: github.com/grafana/imb-db2-prometheus-exporter
build:
    binaries:
        - name: ibm-db2-exporter
          path: ./cmd/ibm-db2-exporter
    flags: -a
    ldflags: |
        -X github.com/prometheus/common/version.Version={{.Version}}
        -X github.com/prometheus/common/version.Revision={{.Revision}}
        -X github.com/prometheus/common/version.Branch={{.Branch}}
        -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
        -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
    files:
        - LICENSE
